---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/docker/sonarr/config:/config
      - /srv/media/tv:/tv #optional
      - /srv/media/downloads/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/docker/radarr/config:/config
      - /srv/media/movies:/movies #optional
      - /srv/media/downloads/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/docker/lidarr/config:/config
      - /srv/media/music:/music #optional
      - /srv/media/downloads/complete:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/docker/sabnzbd/config:/config
      - /srv/media/downloads/incomplete:/incomplete-downloads #optional
      - /srv/media/downloads/complete:/downloads #optional
    ports:
      - 9167:8080
    restart: unless-stopped