services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
      - TORRENTING_PORT=10645
      - WEBUI_USERNAME=admin
      - WEBUI_PASSWORD=pG2oNsKUqR26v8uZ7BAi
    volumes:
      - /srv/docker/qbittorrent/config:/config
      - /srv/media/downloads/complete:/downloads #optional
      - /srv/media/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped